### ISSUE TITLE
Support parallel builds

### ISSUE THREAD

**Issue by Robdel12** [percy/exec-action#2]
This would set the `NONCE` as well as the parallel total to `-1` (and use finalize all).

It's unknown if another action will be needed for finalize all, or if the user could just run `npx finalize --all` (probably will become an action)

**Comment by PatrickHeneise** [comment]
I'm using exec-action now with PercyScript. If this comes together, it would be helpful to update the documentation on how to put parallel tests together. For now, I'm just pushing all `PercyScript.run()`'s into a Promise with slightly different wait-times and wait until they're resolved.

**Comment by Robdel12** [comment]
These actions are now deprecated and parallel support has been added to `@percy/cli`: https://github.com/percy/cli/pull/375
