### ISSUE TITLE
`set-env` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by agrobbin** [percy/exec-action#20]
Hi Percy!

Ever since GitHub deprecated [`set-env`](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/), we've been getting deprecation warnings from `exec-action` due, I think, to its dependence on an old version of `@actions/core` (`1.2.0` vs. `1.2.6` or greater).

**Comment by Robdel12** [comment]
Thanks for the issue! Closed with #18 (will be released here shortly too)

**Comment by agrobbin** [comment]
Great, thanks @Robdel12!

**Comment by injms** [comment]
As a tiny follow up to this, the [exec action documentation quick start](https://docs.percy.io/docs/github-actions#quick-start) could be updated to the fixed `percy/exec-action@v0.3.1` rather than the previous version that throws this error.
