### ISSUE TITLE
update node LTS requirement?

### ISSUE THREAD

**Issue by Pomax** [percy/exec-action#22]
The current active LTS is 14, with maintenance-only LTS being 12, but if I update the action.yml to use `node14` instead of `node12`, I get the error `System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node14' is not supported, use 'docker' or 'node12' instead.')`

Does this _really_ need `using: 'node12'` or will this work if the task it is itself used in already uses `actions/setup-node@v2` for node 14 or 15?

**Comment by Robdel12** [comment]
This doesn't look to be a Percy issue: https://github.com/actions/runner/issues/772
